# .github/workflows/deploy.yaml
on: push
env:
  AWS_REGION: "eu-west-2"
  AWS_ACCOUNT_DEV: "679289103098"
#  CDK_OUTDIR: "cdk.out"
# Required for GH OIDC
permissions:
  id-token: write
  contents: read
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node and Cache
        uses: actions/setup-node@v3
        with:
          node-version: 16.18
          cache: npm
      - name: Unit Tests
        run: npm run test
      - name: Create Artifact
        run: npm run synth # often 'npm run build'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
            role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_DEV }}:role/ODICGitHubDeployRole
            role-session-name: odic-github
            aws-region: ${{ env.AWS_REGION }}
      - name: Deploy Artifact to Staging
        run: npx cdk deploy --app "./cdk.out/assembly-Staging" --all --concurrency 10 --method=direct --require-approval never
      - name: Deploy Artifact to Production
        run: npx cdk deploy --app "./cdk.out/assembly-Prod" --all --concurrency 10 --method=direct --require-approval never
